# Numpy : Practice Problem

1)Extract all odd numbers from arr

In [1]:
import numpy as np

In [2]:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

2) Replace all odd numbers in arr with -1

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3) Convert a 1D array to a 2D array with 2 rows

In [6]:
arr=np.arange(10)

In [7]:
np.reshape(arr,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4) Stack arrays a and b vertically

In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [9]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5)Get all items between 5 and 10 from a

In [10]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [11]:
x = a[5<a]
y = x[10>=x]
y

array([ 6,  9, 10])

6) Create a null vector of size 10 but the fifth value which is 1.                                                  
7) Create a vector with values ranging from 10 to 49.                                                                   
8) Create a 10x10 array with random values and find the minimum and maximum values.                                  
9) Create a 3*3 matrix and print it's transpose matrix                                                                    
10) Create two arrays of 2-D and find dot product of it.                                                                                                                          

In [12]:
x = np.zeros(10); x[4]=1

In [13]:
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7)

In [14]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8)

In [15]:
x = np.random.randn(10,10)

In [16]:
x.min()

-2.4367459145954204

In [17]:
x.max()

2.739213281991198

9)

In [18]:
x = np.random.randint(1,5,(3,3))

In [19]:
x

array([[2, 4, 1],
       [3, 3, 1],
       [2, 4, 4]])

In [20]:
x.T

array([[2, 3, 2],
       [4, 3, 4],
       [1, 1, 4]])

In [21]:
np.transpose(x)

array([[2, 3, 2],
       [4, 3, 4],
       [1, 1, 4]])

10)

In [22]:
a = np.random.randint(1,10,(2,2))

In [23]:
a

array([[1, 8],
       [7, 3]])

In [24]:
b = np.random.randint(10,20,(2,2))

In [25]:
b

array([[11, 14],
       [17, 18]])

In [26]:
np.dot(a,b)

array([[147, 158],
       [128, 152]])

11)Compute the maximum for each row in the given array. 

In [27]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [28]:
a.max(axis=1)

array([9, 8, 6, 3, 9])

12)Select 3rd & 5th row and 3rd & 4th columns

In [29]:
data = np.random.randint(10,100,(5,4))
data

array([[25, 70, 68, 26],
       [19, 96, 12, 37],
       [14, 41, 11, 23],
       [93, 14, 69, 77],
       [17, 59, 57, 75]])

In [30]:
data[[2,4],2:4]

array([[11, 23],
       [57, 75]])

13)Convert below matrix into vector

In [31]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [32]:
np.reshape(matrix,(1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

14)The product of two inverse matrix is identical matrix,prove

In [33]:
m = np.array([[2,3],
              [2,4]])

In [34]:
p = np.linalg.inv(m)
p

array([[ 2. , -1.5],
       [-1. ,  1. ]])

In [35]:
q = m.dot(p)
q

array([[1., 0.],
       [0., 1.]])

In [36]:
np.diag(q)

array([1., 1.])

15) Create a matrix from a uniform distribution over [0, 1)

In [37]:
np.random.rand(3,2)

array([[0.29887635, 0.56874553],
       [0.17862432, 0.5325737 ],
       [0.64669147, 0.14206538]])